#!/bin/bash
# This script configures Vercel to use the correct root directory

echo "=================================================="
echo "VERCEL CONFIGURATION FOR SUBDIRECTORY DEPLOYMENT"
echo "=================================================="
echo ""
echo "The dashboard is in: amazon_ppc_dashboard/nextjs_space"
echo ""
echo "To deploy, you MUST set the Root Directory in Vercel:"
echo ""
echo "METHOD 1: Via Vercel Dashboard (EASIEST)"
echo "=========================================="
echo "1. Go to: https://vercel.com/[your-username]/[project-name]/settings"
echo "2. Navigate to: General → Root Directory"
echo "3. Set to: amazon_ppc_dashboard/nextjs_space"
echo "4. Click Save"
echo "5. Go to Deployments and click 'Redeploy'"
echo ""
echo "METHOD 2: Via Vercel CLI with Token"
echo "===================================="
echo "vercel --cwd amazon_ppc_dashboard/nextjs_space --prod"
echo ""
echo "METHOD 3: Create New Project with Correct Settings"
echo "==================================================="
echo "1. Delete existing project in Vercel"
echo "2. Import repository again"
echo "3. BEFORE deploying, expand 'Build and Output Settings'"
echo "4. Set Root Directory: amazon_ppc_dashboard/nextjs_space"
echo "5. Deploy"
echo ""
echo "=================================================="
